//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЧАСТЬ ПЕРВАЯ
        ///
        ///
        ///
        ///
        ///I
        ///
        ///
        ///
        ///
        ///– Eh bien, mon prince. Genes et Lucques ne sont plus que des apanages, des поместья, de la famille Buonaparte. Non, je vous previens, que si vous ne me dites pas, que nous avons la guerre, si vous vous permettez encore de pallier toutes les infamies, toutes les atrocites de cet Antichrist (ma parole, j&apos;y crois) – je ne vous connais plus, vous n&apos;etes plus mon ami, vous n&apos;etes plus мой верный раб, comme vous dites. [Ну, что, князь, Генуа и Лукка стали не больше, как поместьями [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__first_chapter {
            get {
                return ResourceManager.GetString("Vojna_i_mir__first_chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЧАСТЬ ПЕРВАЯ
        ///
        ///
        ///
        ///
        ///I
        ///
        ///
        ///
        ///
        ///– Eh bien, mon prince. Genes et Lucques ne sont plus que des apanages, des поместья, de la famille Buonaparte. Non, je vous previens, que si vous ne me dites pas, que nous avons la guerre, si vous vous permettez encore de pallier toutes les infamies, toutes les atrocites de cet Antichrist (ma parole, j&apos;y crois) – je ne vous connais plus, vous n&apos;etes plus mon ami, vous n&apos;etes plus мой верный раб, comme vous dites. [Ну, что, князь, Генуа и Лукка стали не больше, как поместьями [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__first_chapter_ansi {
            get {
                return ResourceManager.GetString("Vojna_i_mir__first_chapter_ansi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на часть первая
        ///поместья. мой верный раб. ну. что. князь. генуа и лукка стали не больше. как поместьями фамилии бонапарте. нет. я вас предупреждаю. если вы мне не скажете. что у нас война. если вы еще позволите себе защищать все гадости. все ужасы этого антихриста право. я верю. что он антихрист я вас больше не знаю. вы уж не друг мой. вы уж не мой верный раб. как вы говорите. ну. здравствуйте. здравствуйте. я вижу. что я вас пугаю. садитесь и рассказывайте.
        ///так говорила в июле 1805 года известная анна павловн [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__first_chapter_ansi_maximum {
            get {
                return ResourceManager.GetString("Vojna_i_mir__first_chapter_ansi_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation
        ///
        ///
        ///Лев Толстой
        ///
        ///Война и Мир
        ///
        ///Том 1
        ///
        ///
        ///
        ///
        ///
        ///* * *
        ///
        ///
        ///
        ///Том I
        ///
        ///ЧАСТЬ ПЕРВАЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V
        ///
        ///VI
        ///
        ///VII
        ///
        ///VIII
        ///
        ///IX
        ///
        ///X
        ///
        ///XI
        ///
        ///XII
        ///
        ///XIII
        ///
        ///XIV
        ///
        ///XV
        ///
        ///XVI
        ///
        ///XVII
        ///
        ///XVIII
        ///
        ///XIX
        ///
        ///XX
        ///
        ///XXI
        ///
        ///XXII
        ///
        ///XXIII
        ///
        ///XXIV
        ///
        ///XXV
        ///
        ///XXVI
        ///
        ///XXVII
        ///
        ///XXVIII
        ///
        ///
        ///
        ///
        ///
        ///ЧАСТЬ BTОРАЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V
        ///
        ///VI
        ///
        ///VII
        ///
        ///VIII
        ///
        ///IX
        ///
        ///X
        ///
        ///XI
        ///
        ///XII
        ///
        ///XIII
        ///
        ///XIV
        ///
        ///XV
        ///
        ///XVI
        ///
        ///XVII
        ///
        ///XVIII
        ///
        ///XIX
        ///
        ///XX
        ///
        ///XXI
        ///
        ///
        ///
        ///
        ///
        ///ЧАСТЬ ТРЕТЬЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__Tom_1_2_3_4 {
            get {
                return ResourceManager.GetString("Vojna_i_mir__Tom_1_2_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annotation
        ///
        ///
        ///Лев Толстой
        ///
        ///Война и Мир
        ///
        ///Том 1
        ///
        ///
        ///
        ///
        ///
        ///* * *
        ///
        ///
        ///
        ///Том I
        ///
        ///ЧАСТЬ ПЕРВАЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V
        ///
        ///VI
        ///
        ///VII
        ///
        ///VIII
        ///
        ///IX
        ///
        ///X
        ///
        ///XI
        ///
        ///XII
        ///
        ///XIII
        ///
        ///XIV
        ///
        ///XV
        ///
        ///XVI
        ///
        ///XVII
        ///
        ///XVIII
        ///
        ///XIX
        ///
        ///XX
        ///
        ///XXI
        ///
        ///XXII
        ///
        ///XXIII
        ///
        ///XXIV
        ///
        ///XXV
        ///
        ///XXVI
        ///
        ///XXVII
        ///
        ///XXVIII
        ///
        ///
        ///
        ///
        ///
        ///ЧАСТЬ BTОРАЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V
        ///
        ///VI
        ///
        ///VII
        ///
        ///VIII
        ///
        ///IX
        ///
        ///X
        ///
        ///XI
        ///
        ///XII
        ///
        ///XIII
        ///
        ///XIV
        ///
        ///XV
        ///
        ///XVI
        ///
        ///XVII
        ///
        ///XVIII
        ///
        ///XIX
        ///
        ///XX
        ///
        ///XXI
        ///
        ///
        ///
        ///
        ///
        ///ЧАСТЬ ТРЕТЬЯ
        ///
        ///I
        ///
        ///II
        ///
        ///III
        ///
        ///IV
        ///
        ///V        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__Tom_1_2_3_4_ansi {
            get {
                return ResourceManager.GetString("Vojna_i_mir__Tom_1_2_3_4_ansi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///лев толстой
        ///война и мир
        ///том 1
        ///
        ///том 
        ///часть первая
        ///часть орая
        ///часть третья
        ///
        ///том 
        ///лев николаевич толстой
        ///война и мир
        ///том 1
        ///часть первая
        ///поместья. мой верный раб. ну. что. князь. генуа и лукка стали не больше. как поместьями фамилии бонапарте. нет. я вас предупреждаю. если вы мне не скажете. что у нас война. если вы еще позволите себе защищать все гадости. все ужасы этого антихриста право. я верю. что он антихрист я вас больше не знаю. вы уж не друг мой. вы уж не мой верный раб. как вы говорите. ну. здравствуй [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Vojna_i_mir__Tom_1_2_3_4_ansi_maximum_clear {
            get {
                return ResourceManager.GetString("Vojna_i_mir__Tom_1_2_3_4_ansi_maximum_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, что скачали книгу в бесплатной электронной библиотеке TheLib.Ru: http://thelib.ru
        ///
        ///Все книги автора: http://thelib.ru/authors/habbard_ron_leo.html
        ///
        ///Эта же книга в других форматах: http://thelib.ru/books/habbard_ron_leo/vo_mrake_bytiya.html
        ///
        ///Другие книги серии «Миссия Земля»: http://thelib.ru/series/missiya_zemlya.html
        ///
        ///Приятного чтения!
        ///
        ///
        ///
        ///
        ///
        ///Рон Л. Хаббард
        ///
        ///Во Мраке Бытия
        ///
        ///*
        ///
        ///Миссия: Земля # 2
        ///
        ///
        ///Предуведомление Волтарианского Цензора
        ///
        ///Лорд Инвей, Историограф Его Величества, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Хаббард_Рон_Лео {
            get {
                return ResourceManager.GetString("Хаббард_Рон_Лео", resourceCulture);
            }
        }
    }
}
